version: '3'

services:
  # MQTT Broker (Mosquitto)
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: agrisys-mqtt-broker
    ports:
      - "1883:1883"  # MQTT default port
      - "9001:9001"  # WebSockets port
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  # MQTT Web Client (Optional - for debugging)
  mqtt-web-client:
    image: hivemq/mqtt-cli
    container_name: agrisys-mqtt-web-client
    depends_on:
      - mqtt-broker
    command: shell -h mqtt-broker -p 1883
    tty: true
    stdin_open: true
