version: '3'

services:
  # MQTT Broker (Mosquitto)
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: agrisys-mqtt-broker
    ports:
      - "0.0.0.0:1883:1883"  # MQTT default port - exposed to local network
      - "0.0.0.0:9001:9001"  # WebSockets port - exposed to local network
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  # MQTT Web Client (Optional - for debugging)
  mqtt-web-client:
    image: eclipse-mosquitto:latest
    container_name: agrisys-mqtt-web-client
    depends_on:
      - mqtt-broker
    command: sh -c "sleep 5 && mosquitto_sub -h mqtt-broker -p 1883 -t 'agrisys/#' -v"
    tty: true
    stdin_open: true
